import type { Metadata } from 'next';
import { Funnel_Sans, Geist_Mono, Old_Standard_TT } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';

const oldStandard = Old_Standard_TT({
  variable: '--font-old-standard',
  subsets: ['latin'],
  weight: '400',
});

const funnelSans = Funnel_Sans({
  variable: '--font-funnel-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${funnelSans.variable} ${geistMono.variable} ${oldStandard.variable} font-sans antialiased`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          {children}
        </ThemeProvider>{' '}
      </body>
    </html>
  );
}
